### ISSUE TITLE
mind to add a license?

### ISSUE THREAD

**Issue by chilly2go** [JasonAltschuler/KMeansPlusPlus#1]
I have a project where I'd like to use your code (don't want to write it myself again).
Since you did not yet add a license I technically can't use your code. (yes it is KMeans which is nothing you invented)

It would be nice of you to add a license that would allow to use your code. (I'm not interested in anything closed source)

thanks! :)

**Comment by JasonAltschuler** [comment]
You may use my code in your project. Just cite the source in your project's documentation/readme. Enjoy!

**Comment by chilly2go** [comment]
thanks :)
